version: '3'

tasks:
  clean:
    desc: Löscht den Build-Ordner für einen sauberen Neustart
    cmds:
      - rm -rf build/
      - rm -f CMakeUserPresets.json

  setup:
    desc: Installiert alle C++ Dependencies über Conan
    cmds:
   #   - conan profile detect
      - conan install . --build=missing -c tools.system.package_manager:mode=install -c tools.system.package_manager:sudo=True

  build:
    desc: Konfiguriert und kompiliert das Projekt
    cmds:
      - cmake --preset conan-release
      - cmake --build --preset conan-release

  run:
    desc: Führt die kompilierte Applikation aus
    cmds:
      # Durch das cmake_layout liegt die Executable jetzt meistens direkt im Release-Ordner. 
      # (Passe den Namen 'app' hier ggf. an deine CMakeLists.txt an)
      - ./build/Release/app